version: '3'
services:
# ###################################################################################
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"
# ###################################################################################
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: config
    restart: always
    ports:
      - 8888:8888
    logging:
      options:
        max-size: "10m"
        max-file: "10"
# ###################################################################################
  eureka:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: eureka
    restart: always
    depends_on:
      - config
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"
# ###################################################################################
  turbine:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: turbine
    restart: always
    depends_on:
      - config
      - eureka
      - rabbitmq
    ports:
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
# ###################################################################################
  hystrix-dash:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    build: hystrix-dash
    restart: always
    depends_on:
      - config
      - eureka
      - turbine
    ports:
      - 9999:9999
    logging:
      options:
        max-size: "10m"
        max-file: "10"
# ###################################################################################
  resiliente_servico_a:
    build: ./Resiliente.ServicoA
    ports:
      - 2501:80
    depends_on:
      - config
      - eureka
      - rabbitmq
    logging:
      options:
        max-size: "10m"
        max-file: "10"