logging:
  level:
    org.springframework.security: info
feign:
  hystrix:
    enable: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 100000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  sleuth:
    web:
      client:
        enbabled: true
    sampler:
      probability: 1

  cloud:
    stream:
      bindings:
        hystrixStreamOutput:
          destination: spring.cloud.hystrix.stream

management:
  endpoints:
    web.exposure.include: '*'